### ISSUE TITLE
Zbędne klasy dotyczące budowy JSON-a

### ISSUE THREAD

**Issue by jwest** [LukaszDzw/Chat#4]
JSONDecoder.java i Encoder, mogą być zastąpione np. bibliotekę gson, wtedy nie będzie potrzeby istnienia tych dwóch klas w projekcie

**Comment by LukaszDzw** [comment]
Gdybym zastosował gsona to faktycznie mógłbym się pozbyć obiektów takich jak JsonReader, JsonObject czy JsonArrayBuilder. To lepiej by wyglądało, ale i tak zapis do jsona najlepiej gdyby się odbywał w oddzielnej klasie
