### ISSUE TITLE
REST Api do dodawania wpisów

### ISSUE THREAD

**Issue by jwest** [LukaszDzw/Chat#7]
Z tego co pamiętam, umawialiśmy się z każdym zespołem na jakiś rest endpoint, i w waszym przypadku miało być możliwe za pomocą tego endpointu restowego publikowanie wiadomości.

**Comment by LukaszDzw** [comment]
Dużo problemu sprawiło nam same zrobienie takiej webowej aplikacji od 0. Nie mieliśmy nigdy wcześniej do czynienia z aplikacjami webowymi. Będę szczery i mam nadzieję, że nie będziesz miał mi za złe za szczery feedback. Na zajęciach poruszano od razu zagadnienia dosyć zaawansowane, tzn bez wstępu z prostymi przykładami typu hello world i w ogóle wytłumaczeniem idei na prostym przykładzie. Przez to, to co się odbywało na kursie rozumieli tylko ci, którzy interesują się i rozwijają we własnym zakresie typowo w tym kierunku programowania. Wg sylabusa kurs miał dotyczyć bardziej ogólnych zagadnień związanych z javą. Pomijając już sylabusa, bo i tak nikt go nie czyta i nie zwraca uwagi na to. Co do rest api to z początku była taka rozmowa, ale potem mówiliśmy, że zrobimy to przez websockety. W tej chwili nawet nie mam pomysłu od czego zacząć, aby to zrobić poprzez get i post ani od strony javascriptu, ani od strony javy.
